spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WANGHUSHENGRI?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1

logging:
  file: build/wanghushengri.log
